config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get 'pages/home'
  get 'pages/about'
  get 'pages/services'
  get 'pages/portfolio'
  get 'pages/contacts'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def services
  end

  def portfolio
  end

  def contacts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def active_class(path)
        'active' if current_page?(path)
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title><%= yield :page_title %> - My Portfolio</title>

    <%= csrf_meta_tags %> 
    <%= csp_meta_tag %> 

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Menu -->
    <%= render "shared/menu" %>
    <!-- Content -->
    <%= yield %>
    <!-- Footer -->
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for(:page_title, "About me") %>

<!-- About me -->
<%= render "shared/about" %>

app/views/pages/contacts.html.erb
<% content_for(:page_title, "Contacts") %>

<!-- Contacts -->
<%= render "shared/contacts" %>

app/views/pages/home.html.erb
<!-- Home -->
<%= render "shared/home" %>
<!-- About me -->
<%= render "shared/about" %>
<!-- Services -->
<%= render "shared/services" %>
<!-- Portfolio -->
<%= render "shared/portfolio" %>
<!-- Contacts -->
<%= render "shared/contacts" %>

<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/portfolio.html.erb
<% content_for(:page_title, "My portfolio") %>

<!-- Portfolio -->
<%= render "shared/portfolio" %>

app/views/pages/services.html.erb
<% content_for(:page_title, "Services") %>

<!-- Services -->
<%= render "shared/services" %>

app/views/shared/_about.html.erb
<!-- About me -->
<section class="bg-color-light-dark">
  <div class="container">
    <div class="span-title">About Me</div>
    <h2>About Me</h2>
    <div class="row d-flex align-items-center">
      <div class="col-lg-5 col-md-12 mb-4">
        <%= image_tag "about.jpeg", class: "img-fluid rounded" %>
      </div>
      <div class="col-lg-7 col-md-12">
        <h3 class="mb-3">I'm ProgTer Club</h3>
        <h4>Full Stack Ruby on Rails Developer based in Ternopil</h4>
        <p class="mb-5">I design and develop services for customers specializing creating stylish, modern websites, web services and online stores. My passion is to design digital user experiences through meaningful interactions. Check out my Portfolio</p>
        
        <hr>

        <h4 class="mt-5 mb-4">Personal Info</h4>

        <div class="row row-cols-1 row-cols-md-2 g-4 mb-5">
          <div class="col">
            <p>Name: <strong>ProgTer Club</strong></p>
            <p>Address: <strong>Ukraine, Ternopil</strong></p>
            <p>Age: <strong>30</strong></p>
          </div>

          <div class="col">
            <p>Phone: <strong><a href="tel:+380961011010" target="_blanc">+38(096)-101-10-10</a></strong></p>
            <p>Email: <strong><a href="mailto:yourmail@gmail.com">yourmail@gmail.com</a></strong></p>
            <p>Languages: <strong>Ukraine, English</strong></p>
          </div>

        </div>

        <a href="#" class="btn btn-lg btn-outline-danger fw-bold">Download CV</a>

      </div>
    </div>
  </div>
</section>

app/views/shared/_contacts.html.erb
<!-- Contacts -->
<section class="bg-color-dark">
  <div class="container">
    <div class="span-title">Contacts</div>
    <h2>Let's discuss your project</h2>

    <div class="row row-cols-1 row-cols-md-2 g-4 d-flex align-items-center">

      <div class="col">
        <p class="lead mb-5">Connect with me:</p>
        <p class="mb-5">
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-facebook me-2" viewBox="0 0 16 16">
            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
          </svg>
          <a href="https://www.facebook.com/progter" target="_blank">Facebook</a>
        </p>
        <p class="mb-5">
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-phone me-2" viewBox="0 0 16 16">
            <path d="M11 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h6zM5 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H5z"/>
            <path d="M8 14a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
          </svg> 
          <a href="tel:+380961011010" target="_blanc">+38(096)-101-10-10</a>
        </p>
        <p>
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-cursor me-2" viewBox="0 0 16 16">
            <path d="M14.082 2.182a.5.5 0 0 1 .103.557L8.528 15.467a.5.5 0 0 1-.917-.007L5.57 10.694.803 8.652a.5.5 0 0 1-.006-.916l12.728-5.657a.5.5 0 0 1 .556.103zM2.25 8.184l3.897 1.67a.5.5 0 0 1 .262.263l1.67 3.897L12.743 3.52 2.25 8.184z"/>
          </svg> 
          <a href="mailto:yourmail@gmail.com">yourmail@gmail.com</a>
        </p>

      </div>

      <div class="col">
        
        <%= image_tag "contacts.jpeg", class: "img-fluid rounded" %>

      </div>

    </div>
  </div>
</section>

app/views/shared/_footer.html.erb
<footer class="py-5">
  <div class="container text-center">
    © <%= Time.now.year %> All rights reserved by My Portfolio.
  </div>
</footer>

app/views/shared/_home.html.erb
<% content_for(:page_title, "Home page") %>

<!-- Home -->
<header class="d-flex align-items-center">
  <div class="container">
    <div class="row">
      <div class="col-lg-7">
        <h1 class="mb-4"><span>Hello, I’m</span> Kristina</h1>
        <p class="lead">Full Stack Ruby on Rails Developer</p>
        <p class="mb-5">I design and develop services for customers of all sizes, specializing in creating stylish, modern websites, web services and online stores.</p>
        <a href="#portfolio" class="btn btn-lg btn-outline-danger fw-bold px-4 mb-5">See Portfolio</a>
      </div>
    </div>
  </div>
</header>

app/views/shared/_menu.html.erb
<nav class="navbar sticky-top navbar-expand-md navbar-dark">
  <div class="container">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav me-auto">
        <%= link_to 'Home',      root_path,      class: "nav-link #{active_class(root_path)}" %>      
        <%= link_to 'About',     about_path,     class: "nav-link #{active_class(about_path)}" %>      
        <%= link_to 'Services',  services_path,  class: "nav-link #{active_class(services_path)}" %>      
        <%= link_to 'Portfolio', portfolio_path, class: "nav-link #{active_class(portfolio_path)}" %>      
        <%= link_to 'Contacts',  contacts_path,  class: "nav-link #{active_class(contacts_path)}" %>
      </div>
      <a href="#" class="btn btn-outline-danger px-4 fw-bold" data-bs-toggle="modal" data-bs-target="#exampleModal">Contact me</a>
     </div>
    </div>
</nav>

<!-- Modal -->
<div class="modal fade shadow" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    <h3 class="modal-title mb-5" id="exampleModalLabel">Connect with me:</h3>

    <p class="mb-5">
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-facebook me-2" viewBox="0 0 16 16">
        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
      </svg>
      <a href="https://www.facebook.com/progter" target="_blank">Facebook</a>
    </p>
    <p class="mb-5">
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-phone me-2" viewBox="0 0 16 16">
        <path d="M11 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h6zM5 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H5z"/>
        <path d="M8 14a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
      </svg>
      <a href="tel:+380961011010" target="_blanc">+38(096)-101-10-10</a>
    </p>
    <p class="mb-5">
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-cursor me-2" viewBox="0 0 16 16">
        <path d="M14.082 2.182a.5.5 0 0 1 .103.557L8.528 15.467a.5.5 0 0 1-.917-.007L5.57 10.694.803 8.652a.5.5 0 0 1-.006-.916l12.728-5.657a.5.5 0 0 1 .556.103zM2.25 8.184l3.897 1.67a.5.5 0 0 1 .262.263l1.67 3.897L12.743 3.52 2.25 8.184z"/>
      </svg> 
      <a href="mailto:yourmail@gmail.com">yourmail@gmail.com</a>
    </p>

    <button type="button" class="btn btn-lg btn-outline-danger" data-bs-dismiss="modal">Close</button>
    </div>
  </div>
</div>

app/views/shared/_portfolio.html.erb
<!-- Portfolio -->
<section class="bg-color-light-dark">
  <div class="container">
    <div class="span-title" id="portfolio">Portfolio</div>
    <h2>My Portfolio</h2>

    <div class="row row-cols-1 row-cols-md-2 g-4">

      <div class="col">
        <div class="portfolio-card h-100">
          <%= image_tag "portfolio.jpg", class: "card-img" %>
          <div class="card-body">
            <h4>Site description...</h4>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="portfolio-card h-100">
          <%= image_tag "portfolio.jpg", class: "card-img-top" %>
          <div class="card-body">
            <h4>Site description...</h4>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="portfolio-card h-100">
          <%= image_tag "portfolio.jpg", class: "card-img" %>
          <div class="card-body">
            <h4>Site description...</h4>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="portfolio-card h-100">
          <%= image_tag "portfolio.jpg", class: "card-img-top" %>
          <div class="card-body">
            <h4>Site description...</h4>
          </div>
        </div>
      </div>

    </div>

  </div>
</section>

app/views/shared/_services.html.erb
<!-- Services -->
<section class="bg-color-dark">
  <div class="container">
    <div class="span-title">Services</div>
    <h2>What I Do</h2>

    <div class="row row-cols-1 row-cols-md-3 g-4">

      <div class="col">
        <div class="services-card h-100">
          <div class="card-body">
            <svg xmlns="http://www.w3.org/2000/svg" width="4rem" height="4rem" fill="currentColor" class="bi bi-currency-dollar" viewBox="0 0 16 16">
              <path d="M4 10.781c.148 1.667 1.513 2.85 3.591 3.003V15h1.043v-1.216c2.27-.179 3.678-1.438 3.678-3.3 0-1.59-.947-2.51-2.956-3.028l-.722-.187V3.467c1.122.11 1.879.714 2.07 1.616h1.47c-.166-1.6-1.54-2.748-3.54-2.875V1H7.591v1.233c-1.939.23-3.27 1.472-3.27 3.156 0 1.454.966 2.483 2.661 2.917l.61.162v4.031c-1.149-.17-1.94-.8-2.131-1.718H4zm3.391-3.836c-1.043-.263-1.6-.825-1.6-1.616 0-.944.704-1.641 1.8-1.828v3.495l-.2-.05zm1.591 1.872c1.287.323 1.852.859 1.852 1.769 0 1.097-.826 1.828-2.2 1.939V8.73l.348.086z"/>
            </svg>
            <h3 class="card-title mb-3">Command Line</h3>
            <p class="card-text">The command line and the shell make up a quick, powerful, text-based interface developers use to more effectively and efficiently communicate with computers.</p>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="services-card h-100">
          <div class="card-body">
            <svg xmlns="http://www.w3.org/2000/svg" width="4rem" height="4rem" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
              <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
            </svg>
            <h3 class="card-title mb-3">Git/GitHub</h3>
            <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="services-card h-100">
          <div class="card-body">
            <svg xmlns="http://www.w3.org/2000/svg" width="4rem" height="4rem" fill="currentColor" class="bi bi-gem" viewBox="0 0 16 16">
              <path d="M3.1.7a.5.5 0 0 1 .4-.2h9a.5.5 0 0 1 .4.2l2.976 3.974c.149.185.156.45.01.644L8.4 15.3a.5.5 0 0 1-.8 0L.1 5.3a.5.5 0 0 1 0-.6l3-4zm11.386 3.785-1.806-2.41-.776 2.413 2.582-.003zm-3.633.004.961-2.989H4.186l.963 2.995 5.704-.006zM5.47 5.495 8 13.366l2.532-7.876-5.062.005zm-1.371-.999-.78-2.422-1.818 2.425 2.598-.003zM1.499 5.5l5.113 6.817-2.192-6.82L1.5 5.5zm7.889 6.817 5.123-6.83-2.928.002-2.195 6.828z"/>
            </svg>
            <h3 class="card-title mb-3">Ruby</h3>
            <p class="card-text">Ruby is a dynamic, general-purpose programming language most commonly used for Web Development.</p>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="services-card h-100">
          <div class="card-body">
            <svg xmlns="http://www.w3.org/2000/svg" width="4rem" height="4rem" fill="currentColor" class="bi bi-code-square" viewBox="0 0 16 16">
              <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
              <path d="M6.854 4.646a.5.5 0 0 1 0 .708L4.207 8l2.647 2.646a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 0 1 .708 0zm2.292 0a.5.5 0 0 0 0 .708L11.793 8l-2.647 2.646a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708 0z"/>
            </svg>
            <h3 class="card-title mb-3">Ruby on Rails</h3>
            <p class="card-text">As one of the most powerful ways to quickly develop web applications, Ruby on Rails has a high relevance and demand in today’s marketplace.</p>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="services-card h-100">
          <div class="card-body">
            <svg xmlns="http://www.w3.org/2000/svg" width="4rem" height="4rem" fill="currentColor" class="bi bi-braces" viewBox="0 0 16 16">
              <path d="M2.114 8.063V7.9c1.005-.102 1.497-.615 1.497-1.6V4.503c0-1.094.39-1.538 1.354-1.538h.273V2h-.376C3.25 2 2.49 2.759 2.49 4.352v1.524c0 1.094-.376 1.456-1.49 1.456v1.299c1.114 0 1.49.362 1.49 1.456v1.524c0 1.593.759 2.352 2.372 2.352h.376v-.964h-.273c-.964 0-1.354-.444-1.354-1.538V9.663c0-.984-.492-1.497-1.497-1.6zM13.886 7.9v.163c-1.005.103-1.497.616-1.497 1.6v1.798c0 1.094-.39 1.538-1.354 1.538h-.273v.964h.376c1.613 0 2.372-.759 2.372-2.352v-1.524c0-1.094.376-1.456 1.49-1.456V7.332c-1.114 0-1.49-.362-1.49-1.456V4.352C13.51 2.759 12.75 2 11.138 2h-.376v.964h.273c.964 0 1.354.444 1.354 1.538V6.3c0 .984.492 1.497 1.497 1.6z"/>
            </svg>
            <h3 class="card-title mb-3">HTML & CSS</h3>
            <p class="card-text">HTML is the foundation of all web pages. It defines the structure of a page, while CSS defines its style.</p>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="services-card h-100">
          <div class="card-body">
            <svg xmlns="http://www.w3.org/2000/svg" width="4rem" height="4rem" fill="currentColor" class="bi bi-bootstrap" viewBox="0 0 16 16">
              <path d="M5.062 12h3.475c1.804 0 2.888-.908 2.888-2.396 0-1.102-.761-1.916-1.904-2.034v-.1c.832-.14 1.482-.93 1.482-1.816 0-1.3-.955-2.11-2.542-2.11H5.062V12zm1.313-4.875V4.658h1.78c.973 0 1.542.457 1.542 1.237 0 .802-.604 1.23-1.764 1.23H6.375zm0 3.762V8.162h1.822c1.236 0 1.887.463 1.887 1.348 0 .896-.627 1.377-1.811 1.377H6.375z"/>
              <path d="M0 4a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v8a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V4zm4-3a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V4a3 3 0 0 0-3-3H4z"/>
            </svg>
            <h3 class="card-title mb-3">Bootstrap</h3>
            <p class="card-text">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit.</p>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>